[[redirects]]
from = "/api/*"
to = "https://playground.rebuff.ai/api/:splat"
status = 200
force = true

[[redirects]]
from = "/*"
to = "https://rebuff.unicornplatform.page/:splat"
status = 200
force = true

